[package]
name = "warpgrapher-actix"
version = "0.1.0"
authors = ["taylor <taylor.centers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9.0"
actix-http = "1.0.1"
actix-net = "0.2.6"
actix-rt = "1.0.0"
actix-server-config = "0.1.2"
actix-service = "0.4.1"
actix-threadpool = "0.1.1"
actix-web = "2.0.0"
actix-cors = "0.2.0"
clap = "2.32.0"
futures = "0.3.1"
juniper = "0.13.1"
log = "0.4.6"
warpgrapher = "0.2.0"
