version: 1
model:
  - name: User
    props:
      - name: email
        type: String
  - name: Project
    props:
      - name: name
        type: String
    rels:
      - name: users
        nodes: [User]
        list: true
